-- begin PROJECT_COUNTERAGENTS
create unique index IDX_PROJECT_COUNTERAGENTS_UNIQ_REQUISITES on PROJECT_COUNTERAGENTS (REQUISITES)^
-- end PROJECT_COUNTERAGENTS
-- begin PROJECT_SIMPLE_SPRAVOCHNIK
create unique index IDX_PROJECT_SIMPLE_SPRAVOCHNIK_UNIQ_CODE on PROJECT_SIMPLE_SPRAVOCHNIK (CODE)^
-- end PROJECT_SIMPLE_SPRAVOCHNIK
-- begin PROJECT_BANKS
create unique index IDX_PROJECT_BANKS_UNIQ_REQUISITES on PROJECT_BANKS (REQUISITES)^
-- end PROJECT_BANKS
-- begin PROJECT_CURRENCY_EXCHANGE
alter table PROJECT_CURRENCY_EXCHANGE add constraint FK_PROJECT_CURRENCY_EXCHANGE_ON_FIRST_CURRENCY foreign key (FIRST_CURRENCY_ID) references PROJECT_CURRENCY(ID)^
alter table PROJECT_CURRENCY_EXCHANGE add constraint FK_PROJECT_CURRENCY_EXCHANGE_ON_SECOND_CURRENCY foreign key (SECOND_CURRENCY_ID) references PROJECT_CURRENCY(ID)^
create index IDX_PROJECT_CURRENCY_EXCHANGE_ON_FIRST_CURRENCY on PROJECT_CURRENCY_EXCHANGE (FIRST_CURRENCY_ID)^
create index IDX_PROJECT_CURRENCY_EXCHANGE_ON_SECOND_CURRENCY on PROJECT_CURRENCY_EXCHANGE (SECOND_CURRENCY_ID)^
-- end PROJECT_CURRENCY_EXCHANGE
-- begin PROJECT_CURRENCY
alter table PROJECT_CURRENCY add constraint FK_PROJECT_CURRENCY_ON_CURRENCY_EXCHANGE foreign key (CURRENCY_EXCHANGE_ID) references PROJECT_CURRENCY_EXCHANGE(ID)^
create unique index IDX_PROJECT_CURRENCY_UNIQ_SHORTNAME on PROJECT_CURRENCY (SHORTNAME)^
create unique index IDX_PROJECT_CURRENCY_UNIQ_NAME on PROJECT_CURRENCY (NAME)^
create unique index IDX_PROJECT_CURRENCY_UNIQ_CODE on PROJECT_CURRENCY (CODE)^
create index IDX_PROJECT_CURRENCY_ON_CURRENCY_EXCHANGE on PROJECT_CURRENCY (CURRENCY_EXCHANGE_ID)^
-- end PROJECT_CURRENCY
